server_name: Server

# Change gamemode when entering staffmode
gamemode:
  enabled: true
  mode: SURVIVAL

# Set armor for when entering staffmode
armors:
  enabled: true
  sets:
    administrator:
      permission: staffmodex.armor.administrator
      color: RED
    moderator:
      permission: staffmodex.armor.moderator
      color: ORANGE

# Show diamond notification to staff members
diamond-finder:
  enabled: true
  min-streak: 3

ip:
  enabled: true

action_bar:
  enabled: true
  on_freeze: true
  on_staff: true

vanish:
  enabled: true
  on_staff_mode: true
  hooks:
    premiumvanish: true

staffchat:
  enabled: true
  on_staff_mode: true

staffmode:
  enabled: true
  # Restore location when leaving staffmode
  restore_location: true
  # Commands to block during staffmode
  blocked_commands:
  - "/sethome"
  # Effects given when activating Staff Mode
  effects:
    NIGHT_VISION:
      amplifier: 0
      duration: 2147483647
      aliases: ["NIGHT_VISION"]
    JUMP:
      amplifier: 1
      duration: 2147483647
      aliases: ["JUMP", "JUMP_BOOST"]
    SPEED:
      amplifier: 1
      duration: 2147483647
      aliases: ["SPEED"]

report:
  enabled: true

warning:
  enabled: true

helpop:
  cooldown: 60
  enabled: true

freeze:
  enabled: true
  time: 5

examine:
  enabled: true

items:
  fill:
    name: " "
    material:
    - STAINED_GLASS_PANE
    - GRAY_STAINED_GLASS_PANE
    damage: 7
  hotbar:
    cps:
      slot: 6
      enabled: true
      material:
      - CLOCK
      - WATCH
    examine:
      slot: 7
      enabled: true
      material:
      - CHEST
    follow:
      slot: 8
      enabled: true
      material:
      - LEAD
      - LEASH
    freeze:
      slot: 5
      enabled: true
      material:
      - ICE
    phase:
      slot: 0
      enabled: true
      material:
      - COMPASS
    players:
      slot: 3
      enabled: true
      material:
      - PAPER
    r-teleport:
      slot: 1
      enabled: true
      material:
      - ENDER_EYE
      - EYE_OF_ENDER
    stafflist:
      slot: 4
      enabled: true
      material:
      - SKULL_ITEM
      - SKELETON_SKULL
    vanish:
      slot: 2
      enabled: true
      turned_on:
        damage: 10
        material:
        - LIME_DYE
        - INK_SACK
      turned_off:
        damage: 8
        material:
        - GRAY_DYE
        - INK_SACK
    knockback:
      slot: 8
      enabled: false
      material:
      - BLAZE_ROD

redis:
  enabled: false
  scheme: redis
  username: default
  password: dbscyoBwv4Qe1EgUw9CEKCGkMEIXfnyM
  ip: redis-13955.c274.us-east-1-3.ec2.redns.redis-cloud.com
  port: 13955

mysql:
  enabled: false
  url: jdbc:mysql://localhost:3306/database
  username: root
  password: password
